services:
  postgres:
    image: postgres:latest
    container_name: my_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - my_network
    restart: unless-stopped

  pgadmin:
      image: dpage/pgadmin4:latest
      container_name: my_pgadmin
      environment:
        PGADMIN_DEFAULT_EMAIL: admin@example.com
        PGADMIN_DEFAULT_PASSWORD: admin
      ports:
        - "5050:80"
      volumes:
        - pgadmin:/var/lib/pgadmin
      networks:
        - my_network
      restart: unless-stopped

networks:
  my_network:
   driver: bridge

volumes:
  postgres:
  pgadmin: